all:
	echo "Nothing to do here."

completeMatricesDepth1:
	cd RandomWalks && ./random_walks.py ../../results/depth_1/

completeMatricesDepth2:
	cd RandomWalks && ./random_walks.py ../../results/depth_2/
