all:
	echo "Nothing to do here."

completeMatricesDepth1:
	cd RandomWalks && ./random_walks.py ../../results/depth_1/

completeMatricesDepth2:
	cd RandomWalks && ./random_walks.py ../../results/depth_2/

completeMatricesGALength4:
	cd RandomWalks && ./random_walks.py ../../results/ga_length_4/

completeMatricesGALength4PerInd:
	cd RandomWalks && ./random_walks.py ../../results/ga_length_4_per_ind/

compareTPCalculatedVSampledDepth1:
	cd RandomWalks && ./plotting.py compareTPCalculatedVSampled ../../results/depth_1

compareTPCalculatedVSampledDepth2:
	cd RandomWalks && ./plotting.py compareTPCalculatedVSampled ../../results/depth_2

compareTPCalculatedVSampledGALength4:
	cd RandomWalks && ./plotting.py compareTPCalculatedVSampled ../../results/ga_length_4

compareMFPTEstimateRWVExactDepth1:
	cd RandomWalks && ./plotting.py compareMFPTEstimateRWVExact ../../results/depth_1

compareMFPTEstimateRWVExactDepth2:
	cd RandomWalks && ./plotting.py compareMFPTEstimateRWVExact ../../results/depth_2

compareMFPTEstimateRWVExactGALength4:
	cd RandomWalks && ./plotting.py compareMFPTEstimateRWVExact ../../results/ga_length_4

writeSteadyStateDepth1:
	cd RandomWalks && ./plotting.py writeSteadyState ../../results/depth_1

writeSteadyStateDepth2:
	cd RandomWalks && ./plotting.py writeSteadyState ../../results/depth_2

writeSteadyStateGALength4:
	cd RandomWalks && ./plotting.py writeSteadyState ../../results/ga_length_4

makeGridPlotsDepth1:
	cd RandomWalks && ./plotting.py makeGridPlots ../../results/depth_1

makeGridPlotsDepth2:
	cd RandomWalks && ./plotting.py makeGridPlots ../../results/depth_2

makeGridPlotsGALength4:
	cd RandomWalks && ./plotting.py makeGridPlots ../../results/ga_length_4

makeGridPlotsGALength4PerInd:
	cd RandomWalks && ./plotting.py makeGridPlots ../../results/ga_length_4_per_ind

makeCorrelationTableDepth1:
	cd RandomWalks && ./plotting.py makeCorrelationTable ../../results/depth_1 "GP Depth 1"

makeCorrelationTableDepth2:
	cd RandomWalks && ./plotting.py makeCorrelationTable ../../results/depth_2 "GP Depth 2"

makeCorrelationTableGALength4:
	cd RandomWalks && ./plotting.py makeCorrelationTable ../../results/ga_length_4 "GA Length 4"

makeCorrelationTableGALength4PerInd:
	cd RandomWalks && ./plotting.py makeCorrelationTable ../../results/ga_length_4_per_ind "GA Length 4 per-individual"

uniformSampleDepth6:
	cd RandomWalks && ./random_walks.py graphDistances ../../results/uniform_depth_6/

rwSampleDepth6:
	cd RandomWalks && ./random_walks.py graphDistances ../../results/rw_sample_depth_6/

mhSampleDepth6:
	cd RandomWalks && ./random_walks.py graphDistances ../../results/mh_sample_depth_6/

makeMDSIMagesDepth2:
	cd RandomWalks && ./plotting.py makeMDSImages ../../results/depth_2/

makeMDSIMagesGALength4:
	cd RandomWalks && ./plotting.py makeMDSImages ../../results/ga_length_4/

makeMDSIMagesGALength4PerInd:
	cd RandomWalks && ./plotting.py makeMDSImages ../../results/ga_length_4_per_ind/

